[package]
name = "bogie_core"
description = "Core utils for bogie"
authors = ["OwOchlé <romeoboub@gmail.com>"]
readme = "README.md"
repository = "https://github.com/owochle/bogie"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
